// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/scan": {
            "post": {
                "description": "Analyzes one or more URLs and returns a report on their HTTP security headers configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scan"
                ],
                "summary": "Scan URLs for HTTP security headers",
                "parameters": [
                    {
                        "description": "URLs to scan",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ScanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Report"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.ErrorResponse": {
            "description": "Error response",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "urls is required"
                }
            }
        },
        "handler.ScanRequest": {
            "description": "Request body for HTTP header security scan",
            "type": "object",
            "required": [
                "urls"
            ],
            "properties": {
                "bearer_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "insecure": {
                    "type": "boolean",
                    "example": false
                },
                "timeout": {
                    "type": "integer",
                    "example": 10
                },
                "urls": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "https://www.google.com",
                        "https://github.com"
                    ]
                }
            }
        },
        "models.HeaderResult": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "present": {
                    "type": "boolean"
                },
                "recommendation": {
                    "type": "string"
                },
                "severity": {
                    "$ref": "#/definitions/models.Severity"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "models.Report": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ScanResult"
                    }
                },
                "scan_date": {
                    "type": "string"
                }
            }
        },
        "models.ScanResult": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "headers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.HeaderResult"
                    }
                },
                "status_code": {
                    "type": "integer"
                },
                "summary": {
                    "$ref": "#/definitions/models.Summary"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.Severity": {
            "type": "string",
            "enum": [
                "critical",
                "high",
                "medium",
                "low",
                "ok"
            ],
            "x-enum-varnames": [
                "SeverityCritical",
                "SeverityHigh",
                "SeverityMedium",
                "SeverityLow",
                "SeverityOK"
            ]
        },
        "models.Summary": {
            "type": "object",
            "properties": {
                "failed": {
                    "type": "integer"
                },
                "passed": {
                    "type": "integer"
                },
                "score": {
                    "type": "string"
                },
                "total_checks": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "HTTP Header Security Scanner API",
	Description:      "A tool to scan URLs and analyze HTTP security headers configuration",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
